### ISSUE TITLE
Import Story

### ISSUE THREAD

**Issue by Slade1972** [choosatron/choosatron-write#1]
When importing a story using the Twine format / option nothing happens. No files / stories are imported.
Using Choosatron Write V0.1
Using Twine for windows V1.4.2 -> Export Twee Source Code.

**Comment by spleenboy** [comment]
The import was still using older version of the method names for adding choices and passages. Fixed in ba99025..e087f15 on the develop branch.

**Comment by Slade1972** [comment]
Import now functions, however story links are not generated with the import. Are links meant to happen automatically or is it expected that these will need to be manually updated ?

**Comment by spleenboy** [comment]
Links should generate automatically. I was using just one test twine file. I'll try a few more and see if I can reproduce this.

**Comment by spleenboy** [comment]
Slade1972, what format file are you using for the import? I've able to get one to work successfully with .txt files (ones generated by using "Export Source Code") The translator service is written to handle only that style of twine story, so we may have the wrong supported formats listed.

**Comment by Slade1972** [comment]
I updated my Twine version to the latest available and exported the "Twee Source Code" format.  Here is the file I've tried importing. I'd be curious to know if your file differs to mine.

All the passages import, but the [[links]] show up as text, not links.

[Cinderella.tw](https://mega.co.nz/#!vIQUSDCQ!yycCy2VcZWEBmm7kkg6dE0XL2JZ3SgDlwiG3p_kW9WQ)

**Comment by spleenboy** [comment]
That file was helpful. The import method assumed that each choice had a separate id value (as opposed to using the text of the choice itself.) 596839d Resolves this by making the separate id optional.

**Comment by spleenboy** [comment]
On closer inspection, some of the choices still didn't import properly. Twine lets you blend the choice text with ids in a way that still isn't supported. I'll keep this issue open as more updates are made...
